name: Update submodule

# https://github.com/termux/termux-packages/blob/master/.github/workflows/bootstrap_archives.yml

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

# https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
# https://github.com/orgs/community/discussions/25702
# https://github.com/orgs/community/discussions/26560
# https://github.com/actions/checkout/discussions/479

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.BOT_TOKEN }}
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git submodule update --remote
          git commit -am "submodule: update"
          git push
